export {
  BALANCE,
  WAR,
  MAX_TICKS,
  TICKS_PER_ACTION,
  UNIT_CLASSES,
  damageAgainst,
  type UnitClass,
  type UnitStats,
} from "./balance.ts";

export { hashSeed, makeRng, type Rng } from "./rng.ts";

export {
  armyCost,
  battleCol,
  battleRow,
  chebyshev,
  neighbors,
  pathSteps,
  simulate,
  validateArmy,
  type Army,
  type BattleEvent,
  type BattleResult,
  type Placement,
  type Side,
  type UnitSnapshot,
} from "./simulate.ts";

export { generateArmy } from "./army.ts";

export {
  FOOTPRINT,
  MAP,
  MINES,
  START,
  STRAT_COLS,
  STRAT_ROWS,
  at,
  canStep,
  castlePlot,
  castsCliff,
  cellKey,
  findPath,
  findRoute,
  isForest,
  isHigh,
  isHome,
  isLand,
  isOpen,
  isSlope,
  isWalkable,
  level,
  buildSlots,
  mineSlots,
  plateauOf,
  plotCells,
  plotDistance,
  sameCell,
  stepsFrom,
  tileDistance,
  type BuildingKind,
  type Cell,
  type Mine,
  type Plot,
  type WarSide,
} from "./island.ts";

export {
  SIDES,
  applyAction,
  applyInPlace,
  applyPlan,
  buildingHp,
  canPlace,
  enemyOf,
  findPlacement,
  freeBuilders,
  freeIn,
  gatherers,
  healOf,
  incomeFor,
  levelOf,
  maxHp,
  mineById,
  newMatch,
  occupied,
  openMine,
  ownBuildings,
  pawnOrder,
  payIncome,
  plotById,
  rangeOf,
  spreadAround,
  standing,
  supplyCap,
  supplyUsed,
  tilesBeside,
  trainsAt,
  upkeepOf,
  type Action,
  type ActionResult,
  type Building,
  type MatchState,
  type Mode,
  type Order,
  type Plan,
  type Stance,
  type Training,
  type WarUnit,
} from "./war.ts";

export { battle, concede, createSim, finishRound, roundDone, startRound, type BattleOutcome, type RoundReport, type Sim, type WarEvent } from "./battle.ts";
export { AI_EVERY_TICKS, planAi, runAi } from "./ai.ts";
